# Generated by Django 4.2.6 on 2023-10-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField()),
                ("established_at", models.DateField()),
                ("founder", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "companies",
                "ordering": ["established_at"],
            },
        ),
    ]
