# Generated by Django 4.2.6 on 2023-10-08 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("JobPostingApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmitHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("applied", "지원완료"),
                            ("rejected", "불합격"),
                            ("accepted", "합격"),
                        ],
                        max_length=255,
                    ),
                ),
                ("apply_date", models.DateTimeField(auto_now_add=True)),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="JobPostingApp.jobposting",
                    ),
                ),
            ],
        ),
    ]
