# Generated by Django 4.2.6 on 2023-10-05 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("JobPostingApp", "0001_initial"),
        ("UserApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmitHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_posting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="JobPostingApp.jobposting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="UserApp.user"
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "job_posting")},
            },
        ),
    ]
