# Generated by Django 4.2.6 on 2023-10-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubmitHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("job_posting_id", models.IntegerField()),
                ("status", models.CharField(max_length=255)),
                ("apply_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("user_id", "job_posting_id")},
            },
        ),
    ]
